version: '3.8'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - SECRET_KEY=8n0saoi%9vi5b58cc#=g+($$h)s=^o#&-jsm^26&^&l-%s4-vs9
      - DEBUG=1
  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: